services:
  backend:
    build:
      context: ./backend
    container_name: smart-job-backend
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8001
    container_name: smart-job-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
